<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>JD YA HAVAU TI PADAESH</AssemblyName>
    <RootNamespace>JdClicker</RootNamespace>
    <Version>1.1.0</Version>
    <Product>JD YA HAVAU TI PADAESH</Product>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Description>Автонажатие клавиш зелий для Jade Dynasty</Description>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <!-- Один exe без установки .NET -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <SatelliteResourceLanguages>ru</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\pig.png" LogicalName="JdClicker.Assets.pig.png" />
    <EmbeddedResource Include="Assets\app.ico" LogicalName="JdClicker.Assets.app.ico" />
  </ItemGroup>

</Project>
